spring:
  messages:
    baseName: messages
    encoding: UTF-8
    # Не дает свалиться в системную локаль если не найден файл для переданной в MessageSource
    # Если false то будут браться сообщения из дефолтного файла, если true, то из файла соответствующего системной локали
    fallbackToSystemLocale: false

test-file:
  locale: ru-RU # ru-RU en-US
  name: questions_${test-file.locale}.csv
  skipLines: 1
  rightAnswersCountToPass: 3
  question:
    tag: ;
  answer:
    tag: \|
    splitter: '%'